"""Fixed model constraints

Revision ID: 666721f39d7f
Revises: a6e61be2ead8
Create Date: 2025-05-10 15:19:56.136099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666721f39d7f'
down_revision = 'a6e61be2ead8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)

    with op.batch_alter_table('tracking_updates', schema=None) as batch_op:
        batch_op.drop_column('dummy_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    # ### end Alembic commands ###
