"""added reset_token column

Revision ID: 90def4459365
Revises: 27fb98f22de8
Create Date: 2025-05-06 19:22:26.731004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90def4459365'
down_revision = '27fb98f22de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
