"""empty message

Revision ID: a6e61be2ead8
Revises: 90def4459365
Create Date: 2025-05-10 10:36:45.138607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e61be2ead8'
down_revision = '90def4459365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=20), nullable=False))
        batch_op.drop_column('dummy_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
