"""Add first_name and second_name to users table

Revision ID: 6d467b223c71
Revises: 99397583828a
Create Date: 2025-04-28 18:07:27.988698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d467b223c71'
down_revision = '99397583828a'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns with a default value to handle existing rows
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('second_name', sa.String(length=80), nullable=False, server_default='Unknown'))

    # Remove the server default after ensuring all rows have a value
    op.alter_column('users', 'first_name', server_default=None)
    op.alter_column('users', 'second_name', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('second_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###



