"""Forcing schema detection

Revision ID: 2ad80657482e
Revises: 
Create Date: 2025-05-06 14:41:07.992159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad80657482e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('parcels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parcels_pkey')
    )
    # ### end Alembic commands ###
