"""empty message

Revision ID: 88512b3ef1ba
Revises: 
Create Date: 2025-04-30 17:41:03.737262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88512b3ef1ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_address', sa.String(length=200), nullable=False),
    sa.Column('destination_address', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('present_location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcels')
    # ### end Alembic commands ###
