"""Add coordinate fields

Revision ID: f3c71ef366d9
Revises: cc57a065efef
Create Date: 2025-05-01 22:23:53.928403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c71ef366d9'
down_revision = 'cc57a065efef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('destination_lon')
        batch_op.drop_column('destination_lat')
        batch_op.drop_column('pickup_lon')
        batch_op.drop_column('pickup_lat')

    # ### end Alembic commands ###
