"""Added fields

Revision ID: ff651a9dbc79
Revises: 3abce164d020
Create Date: 2025-05-07 23:29:17.719148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff651a9dbc79'
down_revision = '3abce164d020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
