"""Add weight and description fields

Revision ID: cc57a065efef
Revises: 88512b3ef1ba
Create Date: 2025-05-01 07:52:57.772832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc57a065efef'
down_revision = '88512b3ef1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False,server_default='0.0'))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
